export const HISTORY_CONSTANTS = {
  MAX_ENTRIES: 50,
  RECENT_ENTRIES_COUNT: 3,
  THUMBNAIL_MAX_SIZE: 200,
  GRID_COLUMNS: 3,
  ANIMATION_STAGGER_MS: 50,
  ANIMATION_RECENT_MS: 100,
} as const;

export const ROTATION_ANGLES = [-10, 0, 10] as const;
